### ISSUE TITLE
Cryptic Fail on init files

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_chipseq#160]
```
> pigx-chipseq --init
> pigx-chipseq -s settings.yaml sample_sheet.csv
Traceback (most recent call last):
  File "/home/agosdsc/projects/pigx/pigx_chipseq/vault/.guix-profile/bin/pigx-chipseq", line 334, in <module>
    generate_config(args.configfile,
  File "/home/agosdsc/projects/pigx/pigx_chipseq/vault/.guix-profile/bin/pigx-chipseq", line 149, in generate_config
    update_config(settings,yaml.safe_load(open(settingsfile, 'r')))
  File "/gnu/store/9y7q6ysd21v39pkgkc209f68mpj6s8dr-snakemake-5.7.1/lib/python3.8/site-packages/snakemake/utils.py", line 468, in update_config
    _update(config, overwrite_config)
  File "/gnu/store/9y7q6ysd21v39pkgkc209f68mpj6s8dr-snakemake-5.7.1/lib/python3.8/site-packages/snakemake/utils.py", line 461, in _update
    for (key, value) in u.items():
```

**Comment by alexg9010** [comment]
The problem is that in the initiated settings file, everything is commented out and thus not readable, leading to this erro when we try to update the global settings.   

We should check if in the settings file, there is any line without comment, and if not fail safely. 

https://github.com/BIMSBbioinfo/pigx_chipseq/blob/f99b199610b24dcd7580b97979a420926c8f7e44/pigx-chipseq.in#L152-L153
