### ISSUE TITLE
Can't build DAG

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_chipseq#32]
I believe the `dot` package is missing from the environment here, and as such I can't build the DAG. Error output shown below. Maybe we just need to add it to the scheme file?

```
$ ./pigx-chipseq Tests/sample_sheet.yaml -s  Tests/settings.yaml --graph chip_DAG.pdf
Commencing snakemake run submission locally
Traceback (most recent call last):
  File "./pigx-chipseq", line 311, in <module>
    p2 = subprocess.Popen(['dot','-Tpdf'], stdin=p1.stdout, stdout=outfile)
  File "/gnu/store/jb3n0bsdpkhvyb8y70jyr8fcx8fqssr9-python-3.5.3/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/gnu/store/jb3n0bsdpkhvyb8y70jyr8fcx8fqssr9-python-3.5.3/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'
```

**Comment by Blosberg** [comment]
Loading graphviz into the environment ad-hoc seems to work for this.
