### ISSUE TITLE
update manual: locale error

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_chipseq#99]
- add section about locale error and how to fix it using guix

**Comment by alexg9010** [comment]
If you get an error:

```
##########################

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LC_MEASUREMENT = "de_DE.UTF-8",
    LC_PAPER = "de_DE.UTF-8",
    LC_MONETARY = "de_DE.UTF-8",
    LC_NAME = "de_DE.UTF-8",
    LC_ADDRESS = "de_DE.UTF-8",
    LC_NUMERIC = "de_DE.UTF-8",
    LC_TELEPHONE = "de_DE.UTF-8",
    LC_IDENTIFICATION = "de_DE.UTF-8",
    LC_TIME = "de_DE.UTF-8",
    LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

##########################
```

and the pipeline breaks at multiqc, printing this into the Log :

```
####################################################
Traceback (most recent call last):
  File "/gnu/store/gaijkjaiv4hirsazalpbjp3ifymybkzb-multiqc-1.5/bin/.multiqc-real", line 767, in <module>
    multiqc()
  File "/gnu/store/2h1kcjw1r1306chd45452kwqzq2xb001-python-click-6.7/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/gnu/store/2h1kcjw1r1306chd45452kwqzq2xb001-python-click-6.7/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/gnu/store/2h1kcjw1r1306chd45452kwqzq2xb001-python-click-6.7/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

Additional information: on this system no suitable UTF-8
locales were discovered.  This most likely requires resolving
by reconfiguring the locale system.

Click discovered that you exported a UTF-8 locale
but the locale system could not pick up from it because
it does not exist.  The exported locale is "en_US.UTF-8" but it
is not supported

#######################################################
```

**Comment by alexg9010** [comment]
You have to install `glibc-locales`

```
guix package -i glibc-locales
```

**Comment by alexg9010** [comment]
set the global variable to use these guix locales:

```
export GUIX_LOCPATH=$HOME/.guix-profile/lib/locale
```

**Comment by alexg9010** [comment]
If this is supposed to happen automatically you might consider adding this to your `~/.bashrc` or `~/.bash_profile`.
